AptTest/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from AptTest import views

app_name = 'AptTest'

urlpatterns = [

path('first-question/<int:pk>/', views.first_question_view, name = 'first_question'), 
path('question/<int:pk>/', views.questions, name = 'question'),
path('start/', views.start_quiz, name= 'start_quiz'),
path('apt-test/<int:pk>/result', views.apt_results, name = 'results'),
path('school-sub/', views.school_sub_question, name = 'school_sub_question'),



]

LaunchPad/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from . import views


urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('quiz/', include('AptTest.urls')),
    path('registration/', include('registration.urls'))
    
]







# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns = [
#         path('__debug__', include(debug_toolbar.urls))
#     ] + urlpatterns

AptTest/models.py
from django.db import models
from django.contrib.auth.models import User
import json

HOLLAND_CODE_CHOICES = [
    'Realistic',
    'Investigative',
    'Artistic',
    'Social',
    'Enterprising',
    'Conventional'

]

WORK_ACTIVITIES = [
    'Getting Information', 'Thinking Creatively', 'Processing Information', 'Working with Computers', 
    'Handling and Moving Objects', 'Training and Teaching Others', 'Analyzing Data or Information', 
    'Developing and Building Teams', 'Selling or Influencing Others', 'Staffing Organizational Units',
    'Coaching and Developing Others', 'Scheduling Work and Activities', 'Assisting and Caring for Others',
    'Documenting/Recording Information', 'Controlling Machines and Processes', 'Developing Objectives and Strategies',
    'Monitoring and Controlling Resources', 'Performing Administrative Activities', 'Making Decisions and Solving Problems', 
    'Updating and Using Relevant Knowledge', 'Performing General Physical Activities', 'Identifying Objects, Actions, and Events', 
    'Organizing, Planning, and Prioritizing Work', 'Providing Consultation and Advice to Others', 'Coordinating the Work and Activities of Others', 
    'Inspecting Equipment, Structures, or Materials', 'Repairing and Maintaining Electronic Equipment', 'Repairing and Maintaining Mechanical Equipment', 
    'Guiding, Directing, and Motivating Subordinates', 'Resolving Conflicts and Negotiating with Others', 'Monitoring Processes, Materials, or Surroundings',
    'Communicating with People Outside the Organization', 'Interpreting the Meaning of Information for Others', 
    'Performing for or Working Directly with the Public', 'Operating Vehicles, Mechanized Devices, or Equipment',
    'Judging the Qualities of Objects, Services, or People', 'Communicating with Supervisors, Peers, or Subordinates',
    'Establishing and Maintaining Interpersonal Relationships', 'valuating Information to Determine Compliance with Standards',
    'Drafting, Laying Out, and Specifying Technical Devices, Parts, and Equipment', 'Estimating the Quantifiable Characteristics of Products, Events, or Information'

]

INTEREST_LEVEL = [
    (-2, 'Strongly Dislike'),
    (-1, 'Dislike'),
    (0, 'Unsure'),
    (1, 'Like'),
    (2, 'Strongly Like')
]
QUESTION_TYPES = [
     (1, 'Holland Code'),
    (2, 'Job Zone'),
    (3, 'Work Activities'),
    (4, 'General Skills'),
    
    
]


JOB_ZONE_CHOICES = [
      (1,"Some High School"),
      (2, "High School Diploma or GED"),
      (3, "Associate's Degree or Vocational School"),
      (4, "Bachelor's Degree"), 
      (5, "Master's Degree or Higher")
    ]

def json_as_percent(json_obj):
        result_as_perc = {}
        total_value = 0
        for key, value in json_obj:
            total_value += value
           
        for key, value in json_obj:
            result_as_perc[key] = round((value/total_value) * 100, 2)
       
        return result_as_perc

def get_top_results(input_data_dict, num_of_results):
        sorted_data =  dict(sorted(input_data_dict.items(), key=lambda x: x[1], reverse=True))
        top_traits_list= list(sorted_data.items())[:num_of_results]
        top_traits = [trait[0] for trait in top_traits_list]
        return top_traits

class Career(models.Model):
    name = models.CharField(max_length=256, null= True)
    holland_code_scores= models.JSONField(default=dict)
    holland_code_as_perc = models.JSONField(default=dict)
    job_zone = models.IntegerField(default=0)
    work_activities= models.JSONField(default=dict)
    work_activities_as_perc = models.JSONField(default=dict)
    


    def __str__(self):
        return self.name
    
    def holland_code_perc(self):
        return json_as_percent(self.holland_code_scores.items())
    
    
    def get_top_two_holland(self):
        return get_top_results(self.holland_code_as_perc, 2)
      
    
    def get_top_five_work_activites(self):
        return get_top_results(self.work_activities_as_perc, 5)
   

    

    
    


    
    




class Question(models.Model):
    question = models.CharField(max_length=200,null=True)
    json_choices = models.JSONField(default=dict, )
    trait_pos = models.CharField(max_length=350, null= True)
    question_type = models.IntegerField(choices=QUESTION_TYPES, default=1)
   
    
    
    
    def __str__(self):
        return self.question
    
    
    

    def score_ans(self, answer_obj, CHOICES):
            pts = int(answer_obj.answer)
            ans = ('', pts)
            if '-' in self.trait_pos:
                trait_pos_list = self.trait_pos.split("-")
            else:
                trait_pos_list = self.trait_pos
            traits = []
            for value in CHOICES:
                if value in trait_pos_list:
                    traits.append(value)

                    ans = (traits, pts)
            
            return ans




class Quiz(models.Model):
    name = models.CharField(max_length=256, default= 'quiz')
    user = models.ForeignKey(User, default= 1, on_delete= models.CASCADE)
    questions = models.ManyToManyField('Question', related_name= 'quiz_questions')
    starter_questions = models.ManyToManyField('Question', related_name= 'starter_questions')
    num_of_qs_left = models.IntegerField(default=10)
    score_key = models.JSONField(default=dict)
   
    

    def __str__(self):
        return self.name + ' for ' + str(self.user)
    #TODO make this work
    def generate_question(self):
        return [2,4,6,8]


class Answer(models.Model):
    user = models.ForeignKey(User, on_delete= models.CASCADE)
    question = models.ForeignKey(Question, on_delete= models.CASCADE)
    answer = models.TextField(max_length= 256, null = True, default = 0)

    def __str__(self):
        return str(self.user) + " answer to " + str(self.question)



    
    
class Result(models.Model):
    user = models.ForeignKey(User, on_delete= models.CASCADE)
    quiz = models.ForeignKey(Quiz, on_delete= models.CASCADE)
    holland_result = models.JSONField(default=dict)
    holland_result_as_percent = models.JSONField(default=dict)
    job_zone = models.IntegerField(choices= JOB_ZONE_CHOICES, blank = True, default = 1)
    work_activities = models.JSONField(default= dict)
    work_activities_as_percent = models.JSONField(default=dict)
    questions_asked = models.IntegerField(default=0)
    completed = models.BooleanField(default=False)


    def calc_holland_result_percent(self):
        return json_as_percent(self.holland_result.items())
    
    def calc_work_result_percent(self):
        return json_as_percent(self.work_activities.items())
    
    #TODO use top results to better match
    def career_match(self, all_careers):
        career_match_list = [] # list of tuples(career obj, avg% match to user result)
       
        
        for obj in all_careers:
            holland_result_dict = self.holland_result_as_percent
            holland_career_dict = obj.holland_code_as_perc

            work_act_result_dict = self.work_activities_as_percent
            work_act_career_dict = obj.work_activities_as_perc
            
            holland_common_keys = set(holland_result_dict.keys()) & set(holland_career_dict.keys())
            
    
            work_act_common_keys = set(work_act_result_dict.keys()) & set(work_act_career_dict.keys())

            all_common_keys = holland_common_keys.union(work_act_common_keys)
            
            combined_result_dict = work_act_result_dict | holland_result_dict
            combined_career_dict = work_act_career_dict | holland_career_dict
            
            
            
            percent_diff_dict = {}
            
           
            
            for key in all_common_keys:
                v1 = combined_result_dict[key]
                v2 = combined_career_dict[key]

                diff = v2-v1
                perc_diff = (diff/v1) * 100
                percent_diff_dict[key] = perc_diff

      
            
            all_percents = 0

           
            for v in percent_diff_dict.values():
                all_percents += abs(v)
                avg_perc_diff = all_percents / len(percent_diff_dict)
                
                

            career_obj, user_avg_perc_match = obj, abs(avg_perc_diff-100)
            career_match_list.append((career_obj, round(user_avg_perc_match, 2)))

        
        return career_match_list


            


   
        
       

AptTest/forms.py
from django import forms   
from AptTest.models import Question

# class QuestionForm(forms.ModelForm):
#     class Meta:
#         model = Question
#         fields = ('question',)

AptTest/templates/apt_results.html
{% extends 'base.html' %} 
{% block body_block %}

<div class="container">
    <h1>Here are your results for {{quiz}}</h1>
   
    {% for trait, value in result.result_as_percent.items %}
    {{ trait }} - {{ value }}%<br>
{% endfor %}

<div class="p-2">
    <h2>Careers</h2>
    <ol>
    {% for match in best_matches %} 
    <li>{{match.0}} - {{match.1}}% match</li>
    {% endfor %}
</ol>

</div>














</div>


{% endblock %} 

AptTest/templates/apt_test.html
{% extends 'base.html' %} 
{% block body_block %}



<!DOCTYPE html>
<html>
<head>
    <title>Test</title>
</head>
<body>
    <div class="container">
    <h1 class="p-2">{{quiz.name}}</h1>
        <form method="POST" action="">
            {% csrf_token %}
            {% for q in questions %}
            <div class="py-4 ">
                <div class="p-2">
                    <p>{{q}}</p>
                </div>
                <div class="btn-group" role="group" aria-label="radio toggle button group">
                    <input type="radio" class="btn-check" name="vbtn-radio {{q.pk}}" id="vbtn-radio1 {{q.pk}}" value="{{q.choices.ch1}}" autocomplete="off">
                    <label class="btn btn-outline-danger" for="vbtn-radio1 {{q.pk}}">{{q.choices.ch1}}</label>
                    
                    <input type="radio" class="btn-check" name="vbtn-radio {{q.pk}}" id="vbtn-radio2 {{q.pk}}" value="{{q.choices.ch2}}" autocomplete="off">
                    <label class="btn btn-outline-warning" for="vbtn-radio2 {{q.pk}}">{{q.choices.ch2}}</label>
                    
                    <input type="radio" class="btn-check" name="vbtn-radio {{q.pk}}" id="vbtn-radio3 {{q.pk}}" value="{{q.choices.ch3}}"a utocomplete="off">
                    <label class="btn btn-outline-primary" for="vbtn-radio3 {{q.pk}}">{{q.choices.ch3}}</label>
                    
                    <input type="radio" class="btn-check" name="vbtn-radio {{q.pk}}" id="vbtn-radio4 {{q.pk}}" value="{{q.choices.ch4}}" autocomplete="off">
                    <label class="btn btn-outline-success" for="vbtn-radio4 {{q.pk}}">{{q.choices.ch4}}</label>
                    
                    <input type="radio" class="btn-check" name="vbtn-radio {{q.pk}}" id="vbtn-radio5 {{q.pk}}" value="{{q.choices.ch5}}" autocomplete="off">
                    <label class="btn btn-outline-info" for="vbtn-radio5 {{q.pk}}">{{q.choices.ch5}}</label>
                    <br>
                    
                </div>
            <br>
        </div>
        <hr>
            {% endfor %}
            

            <button type="submit">Submit</button>
        </form>
    </div>
</body>
</html>

{% endblock %}

AptTest/templates/first_questions.html
{% extends 'base.html' %} 
{% block body_block %}



<!DOCTYPE html>
<html>
<head>
    <title>Test</title>
</head>
<body>
    <div class="container">
    <h1 class="p-2">{{quiz.name}}</h1>
        <form method="POST" action="">
            {% csrf_token %}
            
            <div class="py-4 ">
                <div class="p-2">
                    <p>{{question}}</p>
                </div>

                <select class="form-select" aria-label="Default select example" name = "select {{question.pk}}" >
                    <option selected>Select</option>
                    {% for choice, key in choices.items %}
                
                
                    <option value="{{key}}" id="question key {{key}}" >{{choice}}</option>
                    {% endfor %}
                  
                  </select>
            
            <br>
        </div>
        <hr>
           
            

        <div class="p-2">
            <button type="submit" class="btn btn-success ">Next</button>
        </div>
        </form>
    </div>
</body>
</html>

{% endblock %}

AptTest/templates/multi_select_question.html
{% extends 'base.html' %} 
{% block body_block %}



<!DOCTYPE html>
<html>
<head>
    <title>Test</title>
</head>
<body>
    <div class="container">
    <h1 class="p-2">{{question}}</h1>
        <form method="POST" action="">
            {% csrf_token %}
            
            <div class="py-4 ">
               
                <div class="btn-group" role="group" aria-label="radio toggle button group">
                    {% for choice, key in choices.items %}
                    <input type="radio" class="btn-check" name="vbtn-radio" id="{{choice}}" value="{{key}}" autocomplete="off">
                    <label class="btn btn-outline-primary" for="{{choice}}">{{choice}}</label>
                    {% endfor %}
                    
             
                    
                </div>
            <br>
        </div>
        <hr>
           
            
            <div class="p-2">
                <button type="submit" class="btn btn-success ">Next</button>
            </div>
        </form>
        <div class="p-2">
            <a class="btn btn-primary " href="{% url 'AptTest:results' pk=quiz.pk %}">Get Results</a>
        </div>
    </div>
</body>
</html>

{% endblock %}

AptTest/templates/school_subject_question.html
{% extends 'base.html' %} 
{% block body_block %}
<div class="container">
    <div class="p-2">
        <h1>Rate how much you enjoyed each of the following subjects in school</h1>
    </div>
    <div class="p-2">
        <form method="POST" action="">
            {% csrf_token %}
            <label for="customRange1" class="form-label">Math</label>
            <input type="range" class="form-range" name="Subject" id="customRange1">
            <br>
            <label for="customRange1" class="form-label">Science</label>
            <input type="range" class="form-range" name="Subject" id="customRange1">
            <br>
            <label for="customRange1" class="form-label">History</label>
            <input type="range" class="form-range" name="Subject" id="customRange1">
            <br>
            <label for="customRange1" class="form-label">English</label>
            <input type="range" class="form-range" name="Subject" id="customRange1">
            <br>
            <label for="customRange1" class="form-label">Gym</label>
            <input type="range" class="form-range" name="Subject" id="customRange1">
            <div class="p-2">
                <button type="submit" class="btn btn-success ">Next</button>
            </div>
        </form>
        <div class="p-2">
            <a class="btn btn-primary " href="{% url 'AptTest:results' pk=quiz.pk %}">Get Results</a>
        </div>
    </div>
</div>

{% endblock %} 