AptTest/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from AptTest import views

app_name = 'AptTest'

urlpatterns = [

path('first-question/<int:pk>/', views.first_question_view, name = 'first_question'), 
path('question/<int:pk>/', views.questions, name = 'question'),
path('start/', views.start_quiz, name= 'start_quiz'),
path('apt-test/<int:pk>/result', views.apt_results, name = 'results'),
path('school-sub/', views.school_sub_question, name = 'school_sub_question'),



]

LaunchPad/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from . import views


urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('quiz/', include('AptTest.urls')),
    path('registration/', include('registration.urls'))
    
]







# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns = [
#         path('__debug__', include(debug_toolbar.urls))
#     ] + urlpatterns

registration/urls.py
from django.urls import path
from registration import views

from django.contrib.auth import views as auth_views
from django.conf import settings

app_name = 'reg'

urlpatterns = [

path('signup/', views.SignUp.as_view(), name = 'signup'),
path("logout/", auth_views.LogoutView.as_view(), name= 'logout'),
path("login/", views.CustomLogin.as_view(), name = 'login'),
path('profile/', views.CreateProfileView.as_view(), name = 'profile'),
path('profile/update/<int:pk>/', views.UpdateProfileView.as_view(), name = 'update_profile'),

]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    <title>Document</title>
</head>

  <nav class="navbar navbar-expand-md navbar-dark bg-dark" aria-label="Fourth navbar example">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Expand at md</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample04" aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExample04">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Home</a>
          </li>
          
        
          
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled">Disabled</a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown" aria-expanded="false">Hello {{user}}</a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="{% url 'reg:logout' %}">Log Out</a></li>
              <li><a class="dropdown-item" href="{% url 'reg:profile' %}">My Profile</a></li>
              <li><a class="dropdown-item" href="#">Reset Password</a></li>
            </ul>
          </li>
          {% else %} 
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown" aria-expanded="false">Login or Sign up</a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="{% url 'reg:login' %}">Log In</a></li>
              <li><a class="dropdown-item" href="{% url 'reg:signup' %}">Sign Up</a></li>
              
            </ul>
          </li>
          {% endif %}
        </ul>
        <form role="search">
          <input class="form-control" type="search" placeholder="Search" aria-label="Search">
        </form>
      </div>
    </div>
  </nav>
  <br>
  <br>
   
   
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
  <body>
    
    {% block body_block %} 
    {% endblock %} 
    
  </body>

















</html>

templates/home.html
{% extends 'base.html' %} 
{% block body_block %}


<div class="px-4 py-5 my-5 text-center">
    
    <h1 class="display-5 fw-bold text-body-emphasis">Take Our Aptitute Test</h1>
    <div class="col-lg-6 mx-auto">
      <p class="lead mb-4">Find out what job best suits you</p>
      <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
        <a type="button" href="{% url 'AptTest:start_quiz' %}" class="btn btn-primary btn-lg px-4 gap-3">Take Test</a>
        
      </div>
    </div>
  </div>



{% endblock %}